version: "2.6"
services:
  myapp:
    build: .
    ports:
      - "5000:5000"
    networks:
      - mynet
    depends_on:
      - mysql1
  mysql1:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - dbvolume:/var/lib/mysql
    networks:
      - mynet

volumes:
  dbvolume:  

networks:
  mynet: {}  
